In [1]:
import sklearn

In [4]:
sklearn.__version__

'0.24.2'

# 다중공선성 문제?

독립변수들 사이에 상관계수가 높을때 발생하는 문제

독립변수들 사이에 상관계수는 낮아야 하고
독립변수와 종속변수 사이의 상관계수는 높아야 한다.


In [7]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [8]:
iris = load_iris()

In [9]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [10]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [14]:
iris_df['label'] = iris.target

In [15]:
iris_df.sample(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
59                5.2               2.7                3.9               1.4   
68                6.2               2.2                4.5               1.5   

    label  
59      1  
68      1

In [17]:
X_trian, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=11)

In [18]:
X_trian.shape, X_test.shape

((120, 4), (30, 4))

# hyperparameter?

기계학습에서 스스로 학습해낼 수 없는 파라미더를 하이퍼파라미터라고 한다.
하이퍼파라미터를 어떻게 설정하냐에 따라 성능차이가 크게 나므로
이 하이퍼파라미터 튜닝을 잘하는 것이 중요하다.


In [23]:
dt_clf = DecisionTreeClassifier(random_state=11)

In [24]:
dt_clf.fit(X_trian,y_train)

DecisionTreeClassifier(random_state=11)

In [25]:
pred = dt_clf.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy_score(y_test,pred)*100

93.33333333333333

데이터 분리 없이 그냥 모두 학습을 한다면?

In [31]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data,train_label)

DecisionTreeClassifier()

In [32]:
pred = dt_clf.predict(train_data)

In [33]:
accuracy_score(train_label,pred)

1.0

In [34]:
#이미 학습한 데이터는 컴퓨터가 잘 기억할 수 있음
# 새로운 데이터가 들어왔을 때 이 모델이 잘 맞출것인가는 별개의 문제
# 학습데이터와 검증데이터가 분리되어야 함을 잘 보여주는 문제


### K폴드 교차검증



In [35]:
from sklearn.model_selection import KFold
import numpy as np

In [ ]:
iris = load_iris()



dt_clf = DecisionTreeClassifier(random_state=156)



In [39]:
kfold = KFold(n_splits=5,shuffle=True)
cv_accuracy = []

In [40]:
n_iter = 0
for train_index, test_index in kfold.split(iris.data):
    X_train,X_test = iris.data[train_index], iris.data[test_index]
    y_train,y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n{n_iter} 교차검증정확도: {accuracy}, 학습데이터크기 : {train_size}, 검증데이터크기 : {test_size}')
    print(f'{n_iter} 검증데이터 인덱스 {test_index}')
    cv_accuracy.append(accuracy)


1 교차검증정확도: 1.0, 학습데이터크기 : 120, 검증데이터크기 : 30
1 검증데이터 인덱스 [  4  11  12  21  22  25  27  37  40  41  44  45  52  71  74  76  82  91
  92  94  96 114 115 130 134 135 137 143 145 146]

2 교차검증정확도: 0.9333, 학습데이터크기 : 120, 검증데이터크기 : 30
2 검증데이터 인덱스 [  1   5   6   8  14  26  28  29  54  55  57  59  69  73  75  79  81  84
  88  89 104 105 106 112 116 119 121 123 124 142]

3 교차검증정확도: 1.0, 학습데이터크기 : 120, 검증데이터크기 : 30
3 검증데이터 인덱스 [  3  19  32  35  47  48  51  53  58  61  62  63  65  78  85  86  95  97
  98 102 103 118 125 126 127 128 132 133 139 144]

4 교차검증정확도: 0.9667, 학습데이터크기 : 120, 검증데이터크기 : 30
4 검증데이터 인덱스 [  0   2  13  24  30  31  33  34  36  38  49  50  56  60  66  68  72  77
  87  90  93 100 108 113 131 138 141 147 148 149]

5 교차검증정확도: 0.9333, 학습데이터크기 : 120, 검증데이터크기 : 30
5 검증데이터 인덱스 [  7   9  10  15  16  17  18  20  23  39  42  43  46  64  67  70  80  83
  99 101 107 109 110 111 117 120 122 129 136 140]


In [41]:
np.mean(cv_accuracy)

0.9666599999999999

In [42]:
from sklearn.model_selection import StratifiedKFold

In [49]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

skf = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

for train_index,test_index in skf.split(iris.data,iris.target):
    X_train,X_test = iris.data[train_index], iris.data[test_index]
    y_train,y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n{n_iter} 교차검증정확도: {accuracy}, 학습데이터크기 : {train_size}, 검증데이터크기 : {test_size}')
    print(f'{n_iter} 검증데이터 인덱스 {test_index}')
    cv_accuracy.append(accuracy)
    


1 교차검증정확도: 0.98, 학습데이터크기 : 100, 검증데이터크기 : 50
1 검증데이터 인덱스 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

2 교차검증정확도: 0.94, 학습데이터크기 : 100, 검증데이터크기 : 50
2 검증데이터 인덱스 [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

3 교차검증정확도: 0.98, 학습데이터크기 : 100, 검증데이터크기 : 50
3 검증데이터 인덱스 [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


In [ ]:
### 

In [50]:
from sklearn.model_selection import cross_val_score

In [52]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

cross_val_score(dt_clf, iris.data, iris.target, scoring='accuracy', cv=3)

array([0.98, 0.94, 0.98])

In [ ]:
grid_parameters = {'max_depth':[1,2,3],
                  'min_samples_split':[2,3]}



### 레이블 인코딩

In [53]:
from sklearn.preprocessing import LabelEncoder

In [59]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
         
encoder = LabelEncoder()
encoder.fit(items)
encoder.transform(items)


array([0, 1, 4, 5, 3, 3, 2, 2])

In [60]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [61]:
encoder.inverse_transform([0,2,4,5])

array(['TV', '믹서', '전자레인지', '컴퓨터'], dtype='<U5')

In [62]:
from sklearn.preprocessing import OneHotEncoder

In [63]:
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [75]:
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels = labels.reshape(-1,1)
OHencoder = OneHotEncoder()
oharray = OHencoder.fit_transform(labels)
oharray.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [77]:
oharray.shape

(8, 6)

In [78]:
df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})

In [79]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0